Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'ALAMEDA', 423, 30.21);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'ALAMEDA', 206, 14.59);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'ALAMEDA', 62, 4.35);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'ALAMEDA', 124, 8.55);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'ALAMEDA', 354, 24.41);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'ALPINE', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'ALPINE', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'ALPINE', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'ALPINE', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'ALPINE', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'AMADOR', 4, 10.56);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'AMADOR', 11, 29.48);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'AMADOR', 1, 2.74);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'AMADOR', 2, 5.52);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'AMADOR', 1, 2.76);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'BUTTE', 32, 14.55);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'BUTTE', 16, 7.26);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'BUTTE', 3, 1.36);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'BUTTE', 33, 14.87);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'BUTTE', 30, 13.52);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'CALAVERAS', 9, 19.8);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'CALAVERAS', 5, 11.08);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'CALAVERAS', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'CALAVERAS', 2, 4.39);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'CALAVERAS', 17, 37.35);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'COLUSA', 11, 51.2);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'COLUSA', 1, 4.65);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'COLUSA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'COLUSA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'COLUSA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'CONTRA COSTA', 205, 19.48);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'CONTRA COSTA', 114, 10.74);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'CONTRA COSTA', 24, 2.24);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'CONTRA COSTA', 69, 6.37);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'CONTRA COSTA', 463, 42.78);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'DEL NORTE', 16, 56.06);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'DEL NORTE', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'DEL NORTE', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'DEL NORTE', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'DEL NORTE', 2, 7.16);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'EL DORADO', 54, 29.85);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'EL DORADO', 11, 6.09);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'EL DORADO', 3, 1.64);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'EL DORADO', 4, 2.18);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'EL DORADO', 33, 18);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'FRESNO', 550, 58.99);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'FRESNO', 58, 6.17);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'FRESNO', 16, 1.69);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'FRESNO', 44, 4.59);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'FRESNO', 391, 40.78);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'GLENN', 1, 3.55);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'GLENN', 1, 3.54);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'GLENN', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'GLENN', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'GLENN', 1, 3.54);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'HUMBOLDT', 58, 43.07);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'HUMBOLDT', 15, 11.09);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'HUMBOLDT', 1, 0.74);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'HUMBOLDT', 5, 3.71);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'HUMBOLDT', 140, 103.84);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'IMPERIAL', 9, 5.13);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'IMPERIAL', 3, 1.69);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'IMPERIAL', 8, 4.49);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'IMPERIAL', 3, 1.68);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'IMPERIAL', 10, 5.58);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'INYO', 8, 43.17);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'INYO', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'INYO', 1, 5.29);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'INYO', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'INYO', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'KERN', 376, 44.7);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'KERN', 49, 5.77);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'KERN', 2, 0.23);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'KERN', 31, 3.58);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'KERN', 156, 17.99);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'KINGS', 26, 17.03);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'KINGS', 7, 4.61);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'KINGS', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'KINGS', 2, 1.33);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'KINGS', 15, 9.97);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'LAKE', 5, 7.74);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'LAKE', 3, 4.66);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'LAKE', 2, 3.11);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'LAKE', 3, 4.66);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'LAKE', 4, 6.21);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'LASSEN', 1, 2.85);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'LASSEN', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'LASSEN', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'LASSEN', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'LASSEN', 5, 15.28);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'LOS ANGELES', 1303, 14.12);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'LOS ANGELES', 612, 6.61);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'LOS ANGELES', 209, 2.24);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'LOS ANGELES', 342, 3.63);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'LOS ANGELES', 1906, 20.25);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'MADERA', 120, 79.3);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'MADERA', 8, 5.26);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'MADERA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'MADERA', 10, 6.53);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'MADERA', 46, 30.06);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'MARIN', 351, 138.9);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'MARIN', 26, 10.22);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'MARIN', 5, 1.97);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'MARIN', 184, 71.91);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'MARIN', 264, 103.17);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'MARIPOSA', 10, 54.96);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'MARIPOSA', 1, 5.56);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'MARIPOSA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'MARIPOSA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'MARIPOSA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'MENDOCINO', 27, 30.71);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'MENDOCINO', 3, 3.41);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'MENDOCINO', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'MENDOCINO', 6, 6.77);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'MENDOCINO', 10, 11.28);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'MERCED', 131, 51.19);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'MERCED', 27, 10.42);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'MERCED', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'MERCED', 1, 0.38);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'MERCED', 9, 3.42);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'MODOC', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'MODOC', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'MODOC', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'MODOC', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'MODOC', 6, 64.74);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'MONO', 18, 126.43);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'MONO', 2, 13.98);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'MONO', 21, 146.07);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'MONO', 2, 14.11);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'MONO', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'MONTEREY', 132, 31.71);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'MONTEREY', 38, 9.05);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'MONTEREY', 17, 4.03);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'MONTEREY', 49, 11.54);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'MONTEREY', 126, 29.67);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'NAPA', 25, 18.28);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'NAPA', 11, 7.99);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'NAPA', 6, 4.35);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'NAPA', 13, 9.35);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'NAPA', 136, 97.77);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'NEVADA', 23, 23.32);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'NEVADA', 2, 2.03);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'NEVADA', 5, 5.11);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'NEVADA', 70, 71.51);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'NEVADA', 16, 16.34);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'ORANGE', 499, 16.54);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'ORANGE', 142, 4.66);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'ORANGE', 73, 2.37);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'ORANGE', 113, 3.64);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'ORANGE', 445, 14.33);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'PLACER', 80, 22.84);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'PLACER', 19, 5.33);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'PLACER', 11, 3.05);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'PLACER', 86, 23.55);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'PLACER', 122, 33.41);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'PLUMAS', 2, 10.05);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'PLUMAS', 4, 20.06);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'PLUMAS', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'PLUMAS', 1, 5.19);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'PLUMAS', 1, 5.19);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'RIVERSIDE', 467, 21.31);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'RIVERSIDE', 166, 7.48);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'RIVERSIDE', 46, 2.04);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'RIVERSIDE', 80, 3.53);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'RIVERSIDE', 449, 19.8);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SACRAMENTO', 175, 12.32);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SACRAMENTO', 69, 4.82);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SACRAMENTO', 35, 2.44);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SACRAMENTO', 70, 4.84);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SACRAMENTO', 443, 30.6);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SAN BENITO', 7, 12.65);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SAN BENITO', 3, 5.36);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SAN BENITO', 1, 1.76);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SAN BENITO', 1, 1.75);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SAN BENITO', 10, 17.46);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SAN BERNARDINO', 182, 8.93);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SAN BERNARDINO', 115, 5.6);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SAN BERNARDINO', 54, 2.62);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SAN BERNARDINO', 39, 1.88);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SAN BERNARDINO', 195, 9.39);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SAN DIEGO', 1140, 36.74);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SAN DIEGO', 398, 12.73);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SAN DIEGO', 162, 5.14);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SAN DIEGO', 408, 12.82);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SAN DIEGO', 1856, 58.33);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SAN FRANCISCO', 141, 17.49);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SAN FRANCISCO', 70, 8.61);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SAN FRANCISCO', 30, 3.65);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SAN FRANCISCO', 59, 7.1);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SAN FRANCISCO', 117, 14.08);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SAN JOAQUIN', 84, 12.23);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SAN JOAQUIN', 27, 3.9);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SAN JOAQUIN', 15, 2.15);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SAN JOAQUIN', 26, 3.69);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SAN JOAQUIN', 211, 29.98);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SAN LUIS OBISPO', 371, 137.54);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SAN LUIS OBISPO', 15, 5.55);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SAN LUIS OBISPO', 14, 5.17);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SAN LUIS OBISPO', 17, 6.25);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SAN LUIS OBISPO', 44, 16.19);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SAN MATEO', 191, 26.54);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SAN MATEO', 58, 7.97);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SAN MATEO', 23, 3.13);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SAN MATEO', 104, 14);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SAN MATEO', 127, 17.1);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SANTA BARBARA', 66, 15.57);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SANTA BARBARA', 18, 4.23);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SANTA BARBARA', 11, 2.58);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SANTA BARBARA', 28, 6.48);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SANTA BARBARA', 113, 26.14);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SANTA CLARA', 478, 26.76);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SANTA CLARA', 176, 9.74);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SANTA CLARA', 45, 2.46);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SANTA CLARA', 254, 13.7);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SANTA CLARA', 554, 29.89);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SANTA CRUZ', 87, 33.05);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SANTA CRUZ', 22, 8.28);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SANTA CRUZ', 13, 4.84);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SANTA CRUZ', 54, 19.89);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SANTA CRUZ', 161, 59.3);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SHASTA', 32, 18.03);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SHASTA', 27, 15.16);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SHASTA', 2, 1.12);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SHASTA', 7, 3.92);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SHASTA', 30, 16.82);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SIERRA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SIERRA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SIERRA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SIERRA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SIERRA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SISKIYOU', 10, 22.27);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SISKIYOU', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SISKIYOU', 2, 4.41);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SISKIYOU', 5, 11.05);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SISKIYOU', 7, 15.47);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SOLANO', 40, 9.68);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SOLANO', 12, 2.9);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SOLANO', 10, 2.38);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SOLANO', 15, 3.54);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SOLANO', 145, 34.26);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SONOMA', 246, 50.82);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SONOMA', 116, 23.83);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SONOMA', 18, 3.68);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SONOMA', 51, 10.36);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SONOMA', 700, 142.18);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'STANISLAUS', 159, 30.86);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'STANISLAUS', 43, 8.3);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'STANISLAUS', 11, 2.1);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'STANISLAUS', 16, 3.03);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'STANISLAUS', 90, 17.07);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'SUTTER', 5, 5.28);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'SUTTER', 1, 1.06);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'SUTTER', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'SUTTER', 2, 2.06);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'SUTTER', 8, 8.25);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'TEHAMA', 10, 15.75);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'TEHAMA', 1, 1.57);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'TEHAMA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'TEHAMA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'TEHAMA', 38, 59.9);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'TRINITY', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'TRINITY', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'TRINITY', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'TRINITY', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'TRINITY', 5, 37.21);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'TULARE', 230, 51.91);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'TULARE', 77, 17.2);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'TULARE', 27, 5.97);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'TULARE', 25, 5.48);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'TULARE', 38, 8.33);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'TUOLUMNE', 32, 58.03);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'TUOLUMNE', 4, 7.27);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'TUOLUMNE', 1, 1.85);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'TUOLUMNE', 2, 3.68);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'TUOLUMNE', 16, 29.48);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'VENTURA', 372, 45.09);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'VENTURA', 163, 19.63);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'VENTURA', 15, 1.8);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'VENTURA', 36, 4.28);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'VENTURA', 349, 41.53);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'YOLO', 17, 8.44);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'YOLO', 5, 2.47);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'YOLO', 6, 2.93);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'YOLO', 4, 1.94);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'YOLO', 145, 70.32);
Insert into pertussis_rate(year, county_name, cases, rate) values(2010, 'YUBA', 3, 4.15);
Insert into pertussis_rate(year, county_name, cases, rate) values(2011, 'YUBA', 0, 0);
Insert into pertussis_rate(year, county_name, cases, rate) values(2012, 'YUBA', 1, 1.37);
Insert into pertussis_rate(year, county_name, cases, rate) values(2013, 'YUBA', 4, 5.46);
Insert into pertussis_rate(year, county_name, cases, rate) values(2014, 'YUBA', 10, 13.65);
