insert into counties(county_name) values ('LOS ANGELES');
insert into counties(county_name) values ('ORANGE');
insert into counties(county_name) values ('SAN DIEGO');
insert into counties(county_name) values ('RIVERSIDE');
insert into counties(county_name) values ('SAN BERNARDINO');
insert into counties(county_name) values ('SANTA CLARA');
insert into counties(county_name) values ('ALAMEDA');
insert into counties(county_name) values ('SACRAMENTO');
insert into counties(county_name) values ('CONTRA COSTA');
insert into counties(county_name) values ('SAN FRANCISCO');
insert into counties(county_name) values ('VENTURA');
insert into counties(county_name) values ('SAN MATEO');
insert into counties(county_name) values ('FRESNO');
insert into counties(county_name) values ('KERN');
insert into counties(county_name) values ('SONOMA');
insert into counties(county_name) values ('SAN JOAQUIN');
insert into counties(county_name) values ('SOLANO');
insert into counties(county_name) values ('SANTA BARBARA');
insert into counties(county_name) values ('STANISLAUS');
insert into counties(county_name) values ('PLACER');
insert into counties(county_name) values ('SAN LUIS OBISPO');
insert into counties(county_name) values ('MARIN');
insert into counties(county_name) values ('SANTA CRUZ');
insert into counties(county_name) values ('BUTTE');
insert into counties(county_name) values ('MONTEREY');
insert into counties(county_name) values ('EL DORADO');
insert into counties(county_name) values ('TULARE');
insert into counties(county_name) values ('SHASTA');
insert into counties(county_name) values ('YOLO');
insert into counties(county_name) values ('MERCED');
insert into counties(county_name) values ('MADERA');
insert into counties(county_name) values ('HUMBOLDT');
insert into counties(county_name) values ('NEVADA');
insert into counties(county_name) values ('NAPA');
insert into counties(county_name) values ('KINGS');
insert into counties(county_name) values ('IMPERIAL');
insert into counties(county_name) values ('SUTTER');
insert into counties(county_name) values ('CALAVERAS');
insert into counties(county_name) values ('TUOLUMNE');
insert into counties(county_name) values ('TEHAMA');
insert into counties(county_name) values ('YUBA');
insert into counties(county_name) values ('SISKIYOU');
insert into counties(county_name) values ('LAKE');
insert into counties(county_name) values ('SAN BENITO');
insert into counties(county_name) values ('MENDOCINO');
insert into counties(county_name) values ('AMADOR');
insert into counties(county_name) values ('PLUMAS');
insert into counties(county_name) values ('LASSEN');
insert into counties(county_name) values ('DEL NORTE');
insert into counties(county_name) values ('MARIPOSA');
insert into counties(county_name) values ('INYO');
insert into counties(county_name) values ('GLENN');
insert into counties(county_name) values ('MONO');
insert into counties(county_name) values ('COLUSA');
insert into counties(county_name) values ('TRINITY');
insert into counties(county_name) values ('MODOC');
insert into counties(county_name) values ('SIERRA');
insert into counties(county_name) values ('ALPINE');
